export const paymentForms = [
  {
    type: "CREDIT_CARD",
    name: "Cartão Crédito",
    icon: "mdi-credit-card-outline",
  },
  {
    type: "DEBIT_CARD",
    name: "Cartão Débito",
    icon: "mdi-credit-card-outline",
  },
  {
    type: "BANK_TRANSFER",
    name: "Transferência Bancária",
    icon: "mdi-bank-transfer",
  },
  {
    type: "BANK_SLIP",
    name: "Boleto",
    icon: "mdi-barcode",
  },
  {
    type: "CASH",
    name: "Dinheiro",
    icon: "mdi-cash-multiple",
  },
  {
    type: "PIX",
    name: "Pix",
    icon: "mdi-dots-hexagon",
  },
  {
    type: "OTHER",
    name: "Outros",
    icon: "mdi-qrcode-scan",
  },
];

export const transactionTypes = [
  {
    name: "Receita",
    type: "CREDIT",
  },
  {
    name: "Despesa",
    type: "EXPENSE",
  },
  {
    name: "Investimento",
    type: "INVESTMENT",
  },
];

export const materialIconList = [
  { name: "mdi-airplane" },
  { name: "mdi-alarm-panel" },
  { name: "mdi-basket" },
  { name: "mdi-gas-station" },
  { name: "mdi-hospital-building" },
  { name: "mdi-glass-mug-variant" },
  { name: "mdi-home-account" },
  { name: "mdi-currency-usd" },
  { name: "mdi-currency-usd-off" },
  { name: "mdi-basketball" },
  { name: "mdi-access-point-network" },
  { name: "mdi-transmission-tower" },
  { name: "mdi-hamburger" },
  { name: "mdi-fire" },
  { name: "mdi-water-boiler" },
  { name: "mdi-gas-cylinder" },
  { name: "mdi-cart" },
  { name: "mdi-water" },
  { name: "mdi-tshirt-crew" },
  { name: "mdi-book-education" },
  { name: "mdi-laptop" },
  { name: "mdi-mouse" },
  { name: "mdi-headphones" },
  { name: "mdi-cellphone" },
  { name: "mdi-code-greater-than-or-equal" },
  { name: "mdi-apps-box" },
  { name: "mdi-trending-down" },
  { name: "mdi-trending-up" },
  { name: "mdi-car" },
  { name: "mdi-bank" },
  { name: "mdi-credit-card" },
  { name: "mdi-account-cash" },
  { name: "mdi-currency-brl" },
  { name: "mdi-piggy-bank" },
  { name: "mdi-integrated-circuit-chip" },
  { name: "mdi-wallet-plus" },
  { name: "mdi-apps" },
  { name: "mdi-apache-kafka" },
  { name: "mdi-barcode" },
  { name: "mdi-bed-king-outline" },
  { name: "mdi-blur" },
  { name: "mdi-ambulance" },
  { name: "mdi-artstation" },
  { name: "mdi-attachment" },
  { name: "mdi-bike-fast" },
  { name: "mdi-bone" },
  { name: "mdi-cake-variant" },
  { name: "mdi-card-account-details" },
  { name: "mdi-hammer-wrench" },
  { name: "mdi-baguette" },
  { name: "mdi-barley" },
  { name: "mdi-bash" },
  { name: "mdi-yoga" },
  { name: "mdi-storefront" },
  { name: "mdi-steam" },
  { name: "mdi-sofa" },
  { name: "mdi-dog" },
  { name: "mdi-dog-side" },
  { name: "mdi-cat" },
  { name: "mdi-paw" },
  { name: "mdi-cog-outline" },
  { name: "mdi-controller-classic" },
  { name: "mdi-cube" },
  { name: "mdi-diamond-stone" },
  { name: "mdi-moon-waning-crescent" },
  { name: "mdi-moon-new" },
  { name: "mdi-moon-waxing-crescent" },
  { name: "mdi-brightness-6" },
  { name: "mdi-lightbulb" },
  { name: "mdi-lightbulb-on" },
  { name: "mdi-flash" },
  { name: "mdi-mouse" },
  { name: "mdi-cpu-32-bit" },
  { name: "mdi-cpu-64-bit" },
  { name: "mdi-cloud-download" },
  { name: "mdi-cloud-upload" },
  { name: "mdi-code-less-than-or-equal" },
  { name: "mdi-monitor-dashboard" },
  { name: "mdi-desktop-tower-monitor" },
  { name: "mdi-qrcode-scan" },
  { name: "mdi-rhombus-split" },
  { name: "mdi-semantic-web" },
  { name: "mdi-pitchfork" },
  { name: "mdi-movie-open" },
  { name: "mdi-email" },
  { name: "mdi-drag" },
  { name: "mdi-digital-ocean" },
  { name: "mdi-dev-to" },
  { name: "mdi-doorbell-video" },
  { name: "mdi-dialpad" },
  { name: "mdi-diving-snorkel" },
  { name: "mdi-cursor-pointer" },
  { name: "mdi-cross-outline" },
  { name: "mdi-cookie" },
  { name: "mdi-coolant-temperature" },
  { name: "mdi-clover" },
  { name: "mdi-table-furniture" },
  { name: "mdi-chair-rolling" },
  { name: "mdi-shoe-sneaker" },
  { name: "mdi-silverware" },
  { name: "mdi-silverware-fork-knife" },
  { name: "mdi-table-chair" },
  { name: "mdi-boom-gate-up" },
  { name: "mdi-bus-stop-uncovered" },
  { name: "mdi-car-child-seat" },
  { name: "mdi-car-cruise-control" },
  { name: "mdi-cctv" },
  { name: "mdi-cube-outline" },
  { name: "mdi-heart-multiple" },
  { name: "mdi-stethoscope" },
  { name: "mdi-tooth" },
  { name: "mdi-chart-areaspline" },
  { name: "mdi-food-apple" },
  { name: "mdi-sprout" },
];

export const defaultIcon = "mdi-apps-box";
